var s;s=objfieldqueue

x=ds_queue_dequeue(s)
y=ds_queue_dequeue(s)
sprite_index=ds_queue_dequeue(s)
image_xscale=ds_queue_dequeue(s)
image_yscale=ds_queue_dequeue(s)
image_angle=ds_queue_dequeue(s)
visible=ds_queue_dequeue(s)
depth=ds_queue_dequeue(s)

sel=ds_queue_dequeue(s)
grab=ds_queue_dequeue(s)
rotato=ds_queue_dequeue(s)
scaling=ds_queue_dequeue(s)
modified=ds_queue_dequeue(s)
selresize=ds_queue_dequeue(s)
hasfields=ds_queue_dequeue(s)
fieldactive=ds_queue_dequeue(s)
editxy=ds_queue_dequeue(s)
editinst=ds_queue_dequeue(s)
editangle=ds_queue_dequeue(s)
editrad=ds_queue_dequeue(s)
editfid=ds_queue_dequeue(s)
disabled_preview=ds_queue_dequeue(s)
rothandx=ds_queue_dequeue(s)
rothandy=ds_queue_dequeue(s)
draghandx=ds_queue_dequeue(s)
draghandy=ds_queue_dequeue(s)
fieldhandx=ds_queue_dequeue(s)
fieldhandy=ds_queue_dequeue(s)
code=ds_queue_dequeue(s)
uid=ds_queue_dequeue(s)
order=ds_queue_dequeue(s)
obj=ds_queue_dequeue(s)
objname=ds_queue_dequeue(s)
sprw=ds_queue_dequeue(s)
sprh=ds_queue_dequeue(s)
sprox=ds_queue_dequeue(s)
sproy=ds_queue_dequeue(s)
fields=ds_queue_dequeue(s)

speed=0
gravity=0
mask_index=-1
path_end()
