var s;s=objfieldqueue

ds_queue_clear(s)

ds_queue_enqueue(s,x)
ds_queue_enqueue(s,y)
ds_queue_enqueue(s,sprite_index)
ds_queue_enqueue(s,image_xscale)
ds_queue_enqueue(s,image_yscale)
ds_queue_enqueue(s,image_angle)
ds_queue_enqueue(s,visible)
ds_queue_enqueue(s,depth)

ds_queue_enqueue(s,sel)
ds_queue_enqueue(s,grab)
ds_queue_enqueue(s,rotato)
ds_queue_enqueue(s,scaling)
ds_queue_enqueue(s,modified)
ds_queue_enqueue(s,selresize)
ds_queue_enqueue(s,hasfields)
ds_queue_enqueue(s,fieldactive)
ds_queue_enqueue(s,editxy)
ds_queue_enqueue(s,editinst)
ds_queue_enqueue(s,editangle)
ds_queue_enqueue(s,editrad)
ds_queue_enqueue(s,editfid)
ds_queue_enqueue(s,disabled_preview)
ds_queue_enqueue(s,rothandx)
ds_queue_enqueue(s,rothandy)
ds_queue_enqueue(s,draghandx)
ds_queue_enqueue(s,draghandy)
ds_queue_enqueue(s,fieldhandx)
ds_queue_enqueue(s,fieldhandy)
ds_queue_enqueue(s,code)
ds_queue_enqueue(s,uid)
ds_queue_enqueue(s,order)
ds_queue_enqueue(s,obj)
ds_queue_enqueue(s,objname)
ds_queue_enqueue(s,sprw)
ds_queue_enqueue(s,sprh)
ds_queue_enqueue(s,sprox)
ds_queue_enqueue(s,sproy)
