globalvar
    select,selectt
    copyvec,tty,width,height,gridx,gridy,interpolation,
    objpal,instancecount,tilecount,
    codeeditor,view,roomwidth,roomheight,selcol,
    mouse_wx,mouse_wy,mousein,grid,crosshair,zoom,
    removeoutside,fillwithcolor,fillcolor,remember,minimap,mode,
    overlap_check,tile_overlap_check,paladdbuttondown,bg_current,vw_current,ly_current,ly_depth,tilebgpal,
    chunkcrop,chunkleft,chunktop,chunkwidth,chunkheight,grabchunk,sizechunk,chunkloaded,chunkname,
    selection,selleft,seltop,selwidth,selheight,selsize,grabselection,
    theme,buttontex,themebutton,
    jtool_objs,
    objfields,objfieldname,objfieldtype,objfieldargs
    thumbmap,thumbcount
;
